apiVersion: v1
kind: Service
metadata:
  name: restaurantconsumer-service
  namespace: restaurant-dev
  labels:
    app: restaurantconsumer-label
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
  selector:
    app: restaurantconsumer-deployment
